name 'icingaweb2'
version '0.0.1'
author 'Adrian Webb <adrian.webb@coraltech.net>'
license 'Apache License v2'
summary 'Icinga2 Web interface module'
description 'Install, configure and manage the Icinga web interface (Ubuntu)'
project_page 'https://github.com/coralnexus/puppet-icingaweb2'
dependency 'coralnexus/puppet-corl'
dependency 'coralnexus/puppet-git'
dependency 'Icinga/puppet-icinga2'
